spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/javalogin}
    username: ${SPRING_DATASOURCE_USERNAME:javalogin}
    password: ${SPRING_DATASOURCE_PASSWORD:javalogin}

  jpa:
    show-sql: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

server:
  servlet:
    session:
      cookie:
        secure: false

logging:
  level:
    org.springframework.security: INFO
    com.example.javalogin: INFO
